### ISSUE TITLE
add 'interact' to handle IO with convenience

### ISSUE THREAD

**Issue by elisarver** [metrumresearchgroup/command#6]
When calling `Run`, we return `*Pipes` bound to the stdout/stderr pipelines, but buffered in case we try to read past close. When calling `Start()` we return `*Pipes` and the user must later call `Stop` or any long-running process will run forever.

I propose that in order to enhance interactivity, we add a type that handles pipes and termination primitives in one place. This  will allow us to buffer properly, and prevent some of the traps of functions running on unconnected pipes.

```go
type Interact struct {
    *Pipes

    c *Capture
}

// InteractivePipe defines functions on Pipes that handle modes of interaction.
// It is meant as a template, not as a literal interface, an serves an illustration
// of the required interactivity.
type InteractivePipe interface {
    // StdoutScanner returns a bufio.Scanner  that allows the user 
    // to follow stdout output on a line-by-line basis. Since it returns
    // a Scanner, you can use this to change the scan method.
    StdoutScanner() (*bufio.Scanner, error)

    // similar, but with Stderr.
    StderrScanner() (*bufio.Scanner, error)

    // CloseInput is required by some applications to close the input pipe
    // and stop interaction. This signals the application with pipe control
    // that it is OK to exit.
    CloseInput() error
}

// Control defines the process control portion of the command and what
// users can do with it. It is, again, an illustration of possibilities.
type Control interface {
    // Stop immediately cancels the context and tries
    // very hard to kill it.
    Stop() error

    // Wait calls the underlying Wait() function and 
    // will wait indefinitely until a process is finished.
    Wait() error
}

// Interactor is the union of these two interfaces.
type Interactor interface {
    InteractivePipe
    Control
}
```

**Comment by dpastoor** [comment]
👍 gut reaction is this seems to check the boxes of the pain points identified with the current experimentation round very nicely

**Comment by elisarver** [comment]
I may have more to add after running through this first bit, but it's pretty easy to lift this over to the codebase quickly.

**Comment by bkyoung** [comment]
Keep in mind the implicit behavior of an embedded struct.  It serves to promote any interfaces (I.e. behaviors) implemented by the embedded structure to the enclosing structure.  Just keep this in mind.  It is implicit behavior, and will be surprising to someone at some point.  Naming the field avoids the promotion (and therefore implicit behavior).

**Comment by elisarver** [comment]
The types above aren't final, I'm working to find the best approach.

**Comment by elisarver** [comment]
```go

type Interact struct {
	Plumber
	Controller
}

// Plumber defines functions on Pipes that handle modes of interaction.
// It is meant as a template, not as a literal interface, an serves an illustration
// of the required interactivity.
type Plumber interface {
	// RawPipes returns the pipes for direct manipulation by the end-user
	Pipes() *Pipes

	// CloseInput is required by some applications to close the input pipe
	// and stop interaction. This signals the application with pipe control
	// that it is OK to exit.
	CloseInput() error
}

// Controller defines the process control portion of the command and what
// users can do with it. It is, again, an illustration of possibilities.
type Controller interface {
	// Stop immediately cancels the context and tries
	// very hard to kill it.
	Stop() error

	// Wait calls the underlying Wait() function and
	// will wait indefinitely until a process is finished.
	Wait() error
}
```

interfaces ftw

**Comment by elisarver** [comment]
These are implemented on Pipes and Capture, btw.

**Comment by elisarver** [comment]
I moved the *Scanner out of the interface and made them concrete since we had everything we needed to write them in the holding struct.

**Comment by elisarver** [comment]
Consolidating the interactivity down to a set of "hoses" is good stuff, and provides all ways to interact with the application. I like it.

**Comment by elisarver** [comment]
I changed direction on this, and we now wrap *exec.Cmd directly and handle IO in a more convenient way.
